pipeline:
  
  build-master:
    image: 'node:10.6.0'
    commands:
      - 'echo hello'
    when:
      branch: master
  public-online:
    image: plugins/docker
    secrets:
      - docker_username
      - docker_password
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    commands:
      # - - 'docker login --username=13474553441 registry.cn-beijing.aliyuncs.com'
      # - 'docker build --rm -t support-background-manage-system .'
      # - 'docker build --rm -f Dockerfile_master -t support-background-manage-system .'
      - 'docker tag docker_test_01 registry.cn-beijing.aliyuncs.com/my_docker_test_01/docker_test_01:09'
      - 'docker push registry.cn-beijing.aliyuncs.com/my_docker_test_01/docker_test_01:09'
    when:
      branch: master

  