# workspace:
#   base: /drone/src
#   path: ./
pipeline:
  
  build-master:
    image: 'node:10.6.0'
    commands:
      - 'echo hello'
    when:
      branch: master
  public-online:    
    image: plugins/docker 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - 'ls'
      # - 'docker ps'
      - 'docker login --username=hesouli -p Cptbtptp123 registry.cn-beijing.aliyuncs.com'
      # - 'docker ps'
      
      - 'docker build --rm -t docker_test_02 .'
      # - 'docker build --rm -f Dockerfile_master -t support-background-manage-system .'
      - 'docker tag docker_test_02 registry.cn-beijing.aliyuncs.com/my_docker_test_02/docker_test_02'
      - 'docker push registry.cn-beijing.aliyuncs.com/my_docker_test_02/docker_test_02'
    when: 
      branch: master

  