# workspace:
#   base: /drone/src
#   path: ./
pipeline:
  
  build-master:
    image: 'node:10.6.0'
    commands:
      - 'echo hello'
    when:
      branch: master
  public-online:    
    image: plugins/docker 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - 'ls'
      # - 'docker ps'
      - 'docker login --username=hesouli -p Cptbtptp123 registry.cn-beijing.aliyuncs.com'
      # - 'docker ps'
      
      - 'docker build  -t test-docker .'
      # - 'docker build --rm -f Dockerfile_master -t support-background-manage-system .'
      - 'docker tag test-docker registry.cn-beijing.aliyuncs.com/panda-test/test-docker'
      - 'docker push registry.cn-beijing.aliyuncs.com/panda-test/test-docker'
    when: 
      branch: master

  