version: '3'
services:
  drone-server:
    image: drone/drone
    ports:
      - "8082:80"
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=https://39.107.96.198
      - DRONE_DEBUG=true
      - DRONE_GITHUB=true
      - DRONE_GITHUB_PRIVATE_MODE=true
      - DRONE_GITHUB_URL=https://github.com/Blubiubiu/Automated-Public
      - DRONE_GITHUB_CLIENT=a0afc8291c2077baec8e
      - DRONE_GITHUB_SECRET=90ec2278e3b40693afcfff5f6ff613b1c04d49b8
      - DRONE_SECRET=c91b94a603e60e3ef42ef6c7ba4619d37cc552ce
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=c91b94a603e60e3ef42ef6c7ba4619d37cc552ce
  drone-agent:
    image: drone/agent
    depends_on:
      - drone-server
    environment:
      - DRONE_RPC_SERVER=http://drone-server
      - DRONE_RPC_SECRET=c91b94a603e60e3ef42ef6c7ba4619d37cc552ce
      - DRONE_DEBUG=true
      - DOCKER_HOST=tcp://docker-bind:2375
  docker-bind:
     image: docker:dind
     privileged: true